// Auto-generated ABI index file
// WARNING: Do not edit manually. Generated by sync_abis_to_frontend.py
// Run the script after compiling Vyper contracts
// All ABIs are exported as clean arrays compatible with viem

import DateTimeABI from './DateTime.json';
import GovernanceABI from './Governance.json';
import MockUSDCABI from './MockUSDC.json';
import PersonalFundABI from './PersonalFund.json';
import PersonalFundFactoryABI from './PersonalFundFactory.json';
import ProtocolRegistryABI from './ProtocolRegistry.json';
import TokenABI from './Token.json';
import TreasuryABI from './Treasury.json';
import UserPreferencesABI from './UserPreferences.json';

// Central export object
export const ABIS = {
  DateTime: DateTimeABI,
  Governance: GovernanceABI,
  MockUSDC: MockUSDCABI,
  PersonalFund: PersonalFundABI,
  PersonalFundFactory: PersonalFundFactoryABI,
  ProtocolRegistry: ProtocolRegistryABI,
  Token: TokenABI,
  Treasury: TreasuryABI,
  UserPreferences: UserPreferencesABI,
};

// Individual exports
export {
  DateTimeABI,
  GovernanceABI,
  MockUSDCABI,
  PersonalFundABI,
  PersonalFundFactoryABI,
  ProtocolRegistryABI,
  TokenABI,
  TreasuryABI,
  UserPreferencesABI,
};