// Auto-generated TypeScript declarations for ABI imports
// Generated by sync_abis_to_frontend.py

declare module '@/abis/*.json' {
  import { Abi } from 'viem';
  const abi: Abi;
  export default abi;
}
